import { useEffect, useMemo, useState } from "react";
import { isSupabaseConfigured, supabase } from "./lib/supabase";

const stages=[
{id:"foundation",no:"01",weeks:"第 1 周",title:"工程基础补齐",subtitle:"先能独立写出稳定 API，再谈 Agent",color:"blue",skills:["Python：类型、OOP、异常与异步","FastAPI：路由、Pydantic、依赖注入","SQL / MySQL：CRUD、索引与事务","Git、Linux 与 HTTP 基础"],deliverable:"一个带 MySQL 的任务管理 API",interview:"能解释同步/异步、REST、事务和索引"},
{id:"llm",no:"02",weeks:"第 2 周",title:"LLM 应用核心",subtitle:"理解模型能力边界与调用方式",color:"violet",skills:["Prompt：结构化输出与 Few-shot","Token、上下文窗口与成本","Function Calling / Tool Use","流式输出、重试与错误处理"],deliverable:"一个可调用 3 种工具的对话助手",interview:"能讲清 Prompt、Tool Calling 和幻觉治理"},
{id:"rag",no:"03",weeks:"第 3–4 周",title:"RAG 工程",subtitle:"从“能检索”升级为“可评估、可优化”",color:"cyan",skills:["文档解析、切块与 Embedding","向量检索、BM25 与 Hybrid Search","Rerank、Query Rewrite 与引用","召回率、忠实度与离线评测"],deliverable:"带引用和评测集的企业知识库",interview:"能定位检索不准、回答不准分别发生在哪一层"},
{id:"agent",no:"04",weeks:"第 5–6 周",title:"Agent 与 LangGraph",subtitle:"把复杂任务拆成可控的状态机",color:"orange",skills:["Agent Loop 与任务规划","LangGraph State、Node、Edge","Checkpoint、人工确认与中断恢复","Router、多 Agent 与上下文管理"],deliverable:"可恢复、可人工审核的学习辅导 Agent",interview:"能解释为什么复杂流程用 Graph，而不是无限循环"},
{id:"production",no:"05",weeks:"第 7 周",title:"企业化与部署",subtitle:"让 Demo 具备真实交付能力",color:"green",skills:["Docker 与一键部署","Redis 缓存、队列与长任务","SSO / RBAC / 多租户隔离","日志、Tracing、评测与成本监控"],deliverable:"Docker 化、带鉴权和日志的完整服务",interview:"能说明超时、并发、权限和数据隔离如何处理"},
{id:"career",no:"06",weeks:"第 8 周",title:"作品集与面试",subtitle:"把技术能力翻译成业务价值",color:"red",skills:["项目架构图与 3 分钟介绍","STAR 项目故事与故障复盘","AI Agent 高频题与代码题","ROI、MVP 与客户需求拆解"],deliverable:"1 个主项目 + 2 个小 Demo + 中英文自我介绍",interview:"能用“问题—方案—结果—取舍”讲完整项目"}];
const plans={sprint:{label:"8 周求职冲刺",desc:"优先形成可面试、可演示的完整项目",hours:"每天 6–8 小时",days:"56 天"},steady:{label:"12 周系统进阶",desc:"增加基础练习、源码理解和工程深度",hours:"每天 3–4 小时",days:"84 天"}};

export default function Home(){
 const[mode,setMode]=useState("sprint");const[done,setDone]=useState([]);const[active,setActive]=useState("foundation");const[targetDate,setTargetDate]=useState("");
 const[ready,setReady]=useState(false);const[cloudReady,setCloudReady]=useState(false);const[session,setSession]=useState(null);const[syncStatus,setSyncStatus]=useState("仅保存在本机");
 const[email,setEmail]=useState("");const[authMessage,setAuthMessage]=useState("");const[authBusy,setAuthBusy]=useState(false);
 useEffect(()=>{const raw=localStorage.getItem("agent-roadmap-state");const legacy=localStorage.getItem("agent-roadmap-progress");try{if(raw){const x=JSON.parse(raw);setDone(x.done??[]);setMode(x.mode??"sprint");setActive(x.active??"foundation");setTargetDate(x.targetDate??"")}else if(legacy)setDone(JSON.parse(legacy))}catch{setSyncStatus("本地数据读取失败")}setReady(true)},[]);
 useEffect(()=>{if(!supabase)return;supabase.auth.getSession().then(({data})=>setSession(data.session));const{data:{subscription}}=supabase.auth.onAuthStateChange((_event,next)=>setSession(next));return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(!ready||!session||!supabase)return;let cancelled=false;(async()=>{setCloudReady(false);setSyncStatus("正在读取云端数据…");const{data,error}=await supabase.from("user_learning_state").select("completed_tasks,learning_mode,active_stage,target_date").eq("user_id",session.user.id).maybeSingle();if(cancelled)return;if(error){setSyncStatus(`读取失败：${error.message}`);return}if(data){setDone(data.completed_tasks??[]);setMode(data.learning_mode??"sprint");setActive(data.active_stage??"foundation");setTargetDate(data.target_date??"")}else{const local=JSON.parse(localStorage.getItem("agent-roadmap-state")||"{}");setDone(local.done??done);setMode(local.mode??mode);setActive(local.active??active);setTargetDate(local.targetDate??targetDate)}setCloudReady(true);setSyncStatus("已连接 Supabase")})();return()=>{cancelled=true}},[ready,session?.user?.id]);
 useEffect(()=>{if(!ready)return;localStorage.setItem("agent-roadmap-state",JSON.stringify({done,mode,active,targetDate}));if(!session||!supabase||!cloudReady){if(!session)setSyncStatus(isSupabaseConfigured?"登录后可跨设备同步":"仅保存在本机");return}const timer=setTimeout(async()=>{setSyncStatus("正在同步…");const{error}=await supabase.from("user_learning_state").upsert({user_id:session.user.id,completed_tasks:done,learning_mode:mode,active_stage:active,target_date:targetDate||null,updated_at:new Date().toISOString()},{onConflict:"user_id"});setSyncStatus(error?`同步失败：${error.message}`:"已同步到云端")},450);return()=>clearTimeout(timer)},[done,mode,active,targetDate,ready,cloudReady,session?.user?.id]);
 const signIn=async(e)=>{e.preventDefault();if(!supabase||!email)return;setAuthBusy(true);setAuthMessage("");const{error}=await supabase.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.href.split("#")[0]}});setAuthMessage(error?`发送失败：${error.message}`:"登录链接已发送，请打开邮箱完成登录。");setAuthBusy(false)};
 const signOut=async()=>{if(supabase)await supabase.auth.signOut();setCloudReady(false);setSession(null);setAuthMessage("已退出，当前修改将保存在本机。");};
 const all=stages.flatMap(s=>s.skills.map((_,i)=>`${s.id}-${i}`));const percent=Math.round(done.length/all.length*100);const current=stages.find(s=>s.id===active)??stages[0];const toggle=(id)=>setDone(v=>v.includes(id)?v.filter(x=>x!==id):[...v,id]);const stageDone=useMemo(()=>current.skills.filter((_,i)=>done.includes(`${current.id}-${i}`)).length,[current,done]);
 return <main>
  <nav className="nav shell"><a className="brand" href="#top"><span className="brand-mark">A</span><span>AgentPath</span></a><div className="nav-links"><a href="#roadmap">学习路线</a><a href="#workbench">今日计划</a><a href="#principles">学习原则</a></div><a className="nav-cta" href="#roadmap">开始学习 <span>↗</span></a></nav>
  <section className="cloud-bar"><div className="shell cloud-inner"><div><b>{session?"云端同步已开启":"登录后保存到云端"}</b><span className={syncStatus.includes("失败")?"sync-error":""}>{syncStatus}</span></div>{session?<div className="account"><span>{session.user.email}</span><button onClick={signOut}>退出</button></div>:<form onSubmit={signIn}><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="输入邮箱接收登录链接" required/><button disabled={authBusy||!isSupabaseConfigured}>{authBusy?"发送中…":"邮箱登录"}</button></form>}</div>{authMessage&&<p className="shell auth-message">{authMessage}</p>}</section>
  <section className="hero shell" id="top"><div className="hero-copy"><div className="eyebrow"><span>●</span> AI 应用开发 · 实战路线</div><h1>别再收集课程，<br/>开始构建你的 <em>Agent。</em></h1><p>一条为有开发经验的转型者设计的学习路径。从 Python 与 FastAPI，到 RAG、LangGraph 和企业级交付，每一步都有明确产出。</p><div className="hero-actions"><a className="primary" href="#roadmap">查看完整路线 <span>↓</span></a><button className="text-btn" onClick={()=>setMode(mode==="sprint"?"steady":"sprint")}>切换学习节奏 <span>→</span></button></div><div className="trust"><div><b>8</b><span>周冲刺</span></div><i/><div><b>6</b><span>核心阶段</span></div><i/><div><b>3</b><span>项目产出</span></div></div></div>
   <div className="hero-card"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="core"><span>✦</span><b>AGENT</b><small>BUILD · TEST · SHIP</small></div><div className="float-card fc-one"><span>01</span><b>RAG</b><small>检索增强生成</small></div><div className="float-card fc-two"><span>02</span><b>TOOLS</b><small>让模型采取行动</small></div><div className="float-card fc-three"><span>03</span><b>GRAPH</b><small>可控工作流</small></div></div>
  </section>
  <section className="roadmap shell" id="roadmap"><div className="section-head"><div><span className="kicker">YOUR ROADMAP</span><h2>从基础到可交付，<br/>每一阶段都有作品。</h2></div><p>不要平均用力。先完成一个阶段的产出，再进入下一个阶段。点击卡片查看任务并记录进度。</p></div>
   <div className="mode-switch" role="group" aria-label="选择学习路线">{(Object.keys(plans)).map(k=><button key={k} className={mode===k?"selected":""} onClick={()=>setMode(k)}><b>{plans[k].label}</b><span>{plans[k].desc}</span></button>)}<div className="mode-summary"><span>{plans[mode].hours}</span><b>{plans[mode].days}</b></div></div>
   <div className="stage-grid">{stages.map((s,idx)=>{const n=s.skills.filter((_,i)=>done.includes(`${s.id}-${i}`)).length;return <button key={s.id} className={`stage-card ${s.color} ${active===s.id?"active":""}`} onClick={()=>setActive(s.id)}><div className="stage-top"><span>{s.no}</span><small>{s.weeks}</small></div><h3>{s.title}</h3><p>{s.subtitle}</p><div className="mini-progress"><i style={{width:`${n/s.skills.length*100}%`}}/></div><footer><span>{n}/{s.skills.length} 已完成</span><b>{idx<stages.length-1?"→":"✓"}</b></footer></button>})}</div>
  </section>
  <section className="workbench" id="workbench"><div className="shell work-grid"><div className="task-panel"><span className="kicker">LEARNING WORKBENCH</span><h2>{current.no} / {current.title}</h2><p className="stage-lead">{current.subtitle}</p><div className="tasks">{current.skills.map((skill,i)=>{const id=`${current.id}-${i}`,checked=done.includes(id);return <label key={skill} className={checked?"checked":""}><input type="checkbox" checked={checked} onChange={()=>toggle(id)}/><span className="check">{checked?"✓":""}</span><span>{skill}</span></label>})}</div><div className="deliverable"><span>本阶段作品</span><b>{current.deliverable}</b></div></div>
   <aside className="progress-panel"><div className="progress-top"><span>总进度</span><b>{percent}%</b></div><div className="big-progress"><i style={{width:`${percent}%`}}/></div><p>已完成 <b>{done.length}</b> / {all.length} 个核心任务</p><div className="target-date"><label htmlFor="target-date">求职计划目标日期</label><input id="target-date" type="date" value={targetDate} onChange={e=>setTargetDate(e.target.value)}/><span>{targetDate?`计划在 ${targetDate} 前完成路线`:"选择日期后会自动保存"}</span></div><div className="today"><small>完成标准</small><strong>{stageDone===current.skills.length?"本阶段已完成，可以进入下一阶段。":`还差 ${current.skills.length-stageDone} 项，完成后再进入下一阶段。`}</strong></div><div className="interview"><small>面试检验</small><p>{current.interview}</p></div>{done.length>0&&<button className="reset" onClick={()=>setDone([])}>重置全部进度</button>}</aside>
  </div></section>
  <section className="principles shell" id="principles"><div className="section-head"><div><span className="kicker">HOW TO LEARN</span><h2>三个原则，避免<br/>“学了很多，却不会做”。</h2></div></div><div className="principle-grid"><article><span>01</span><h3>项目驱动，而非课程驱动</h3><p>课程只看解决当前问题所需的章节。每周必须产生代码、演示或文档。</p></article><article><span>02</span><h3>先跑通，再解释，再优化</h3><p>第一遍做出结果；第二遍脱离 AI 复现；第三遍才能谈性能与架构取舍。</p></article><article><span>03</span><h3>用面试问题检验理解</h3><p>每学一个概念，都要能用自己的话讲清：为什么用、何时不用、出了问题怎么查。</p></article></div></section>
  <footer className="footer"><div className="shell"><div className="brand"><span className="brand-mark">A</span><span>AgentPath</span></div><p>Build agents. Solve real problems.</p><a href="#top">回到顶部 ↑</a></div></footer>
 </main>
}
